### ISSUE TITLE
mac: Cody Launch error - panic: (bug) frontend configuration server failed to start after 5m0s

### ISSUE THREAD

**Issue by jdelgado-sb** [sourcegraph/app#23]
Hi all, looks different than other issues, so will report. Looks like FE service is failing to launch due to database connection issues.

[cody.log](https://github.com/sourcegraph/app/files/11910347/cody.log)

**Comment by jdelgado-sb** [comment]
Relevant section:
```
[2023-06-29][20:04:13][ERROR][app] ✱ Sourcegraph App version: 2023.6.28+1331.1867679b11
[2023-06-29][20:09:13][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-06-29][20:09:13][ERROR][app]
[2023-06-29][20:09:13][ERROR][app] goroutine 308 [running]:
[2023-06-29][20:09:13][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0x14000010d38?)
[2023-06-29][20:09:13][ERROR][app] 	internal/conf/store.go:175 +0x300
[2023-06-29][20:09:13][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0x14000a066c0)
[2023-06-29][20:09:13][ERROR][app] 	internal/conf/store.go:137 +0x2c
[2023-06-29][20:09:13][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0x140009963c0, 0x10dd99120)
[2023-06-29][20:09:13][ERROR][app] 	internal/conf/client.go:169 +0x1b8
[2023-06-29][20:09:13][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x1400067cd80?)
[2023-06-29][20:09:13][ERROR][app] 	internal/conf/client.go:136 +0x28
[2023-06-29][20:09:13][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-06-29][20:09:13][ERROR][app] 	cmd/symbols/parser/config.go:52 +0x24
[2023-06-29][20:09:13][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-06-29][20:09:13][ERROR][app] 	cmd/symbols/parser/config.go:51 +0xe8
```

**Comment by emidoots** [comment]
Thank you for filing this and trying it out @jdelgado-sb! I really appreciate it

Just to confirm, if you choose the `Clear all data and restart` option (system tray -> cody -> troubleshoot -> clear all data option) - then do you encounter the same thing?

Which OS is this with?

**Comment by hussain4real** [comment]
facing same issue even after `Clear all data and restart`

**Comment by Kiokku** [comment]
same issue on OSX, just tried `Clear all data and restart` several times, and it works!

**Comment by emidoots** [comment]
@hussain4real could you show your logs? I want to see if it is the same error: `panic: (bug) frontend configuration server failed to start after 5m0s`

**Comment by vaibhavkumar-sf** [comment]
Same issue : 

`
[2023-07-20][08:42:44][ERROR][app] Cody app backend terminated with exit code 1
[2023-07-20][08:44:55][ERROR][app::common] No such file or directory (os error 2)
[2023-07-20][08:44:56][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin arm64
[2023-07-20][08:49:56][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 299 [running]:
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0x1400012a5d8?)
[2023-07-20][08:49:56][ERROR][app] 	internal/conf/store.go:175 +0x300
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0x14000723680)
[2023-07-20][08:49:56][ERROR][app] 	internal/conf/store.go:137 +0x2c
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0x14000411bc0, 0x10f2ba070)
[2023-07-20][08:49:56][ERROR][app] 	internal/conf/client.go:169 +0x1b8
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x0?)
[2023-07-20][08:49:56][ERROR][app] 	internal/conf/client.go:136 +0x28
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-07-20][08:49:56][ERROR][app] 	cmd/symbols/parser/config.go:52 +0x24
[2023-07-20][08:49:56][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-07-20][08:49:56][ERROR][app] 	cmd/symbols/parser/config.go:51 +0xe8
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 1 [syscall, 4 minutes]:
[2023-07-20][08:49:56][ERROR][app] syscall.syscall6(0x14001b18928?, 0x2?, 0x1400422f198?, 0x10214a700?, 0x10001c570?, 0x11ad0d218?, 0x113344a68?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/runtime/sys_darwin.go:45 +0x64
[2023-07-20][08:49:56][ERROR][app] syscall.wait4(0x1400422f1d8?, 0x1021446c8?, 0x90?, 0x10f1a5380?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/syscall/zsyscall_darwin_arm64.go:43 +0x4c
[2023-07-20][08:49:56][ERROR][app] syscall.Wait4(0x1400232c570?, 0x1400422f214, 0x10e25a3d8?, 0x1?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/syscall/syscall_bsd.go:144 +0x28
[2023-07-20][08:49:56][ERROR][app] os.(*Process).wait(0x14002308570)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec_unix.go:43 +0x80
[2023-07-20][08:49:56][ERROR][app] os.(*Process).Wait(...)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec.go:132
[2023-07-20][08:49:56][ERROR][app] os/exec.(*Cmd).Wait(0x14001d20420)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:599 +0x3c
[2023-07-20][08:49:56][ERROR][app] os/exec.(*Cmd).Run(0x10545afb3?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:437 +0x38
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.isDockerAvailable()
[2023-07-20][08:49:56][ERROR][app] 	internal/singleprogram/singleprogram.go:237 +0xec
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.Init({0x10f33b970, 0x140014a2f00})
[2023-07-20][08:49:56][ERROR][app] 	internal/singleprogram/singleprogram.go:164 +0xbf4
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main.func3(0x14000d452c0?)
[2023-07-20][08:49:56][ERROR][app] 	internal/service/svcmain/svcmain.go:91 +0x80
[2023-07-20][08:49:56][ERROR][app] github.com/urfave/cli/v2.(*Command).Run(0x14000d452c0, 0x140014a2b40, {0x14000116050, 0x5, 0x5})
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_urfave_cli_v2/command.go:271 +0x78c
[2023-07-20][08:49:56][ERROR][app] github.com/urfave/cli/v2.(*App).RunContext(0x14000571860, {0x10f31e778?, 0x1400012e008}, {0x14000116050, 0x5, 0x5})
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:333 +0x5a4
[2023-07-20][08:49:56][ERROR][app] github.com/urfave/cli/v2.(*App).Run(...)
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:310
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main({0x111abeec0, 0xd, 0xd}, {0x64?, 0x0?}, {0x14000116050?, 0x5, 0x5})
[2023-07-20][08:49:56][ERROR][app] 	internal/service/svcmain/svcmain.go:102 +0x620
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd.MainEnterprise(...)
[2023-07-20][08:49:56][ERROR][app] 	enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go:15
[2023-07-20][08:49:56][ERROR][app] main.main()
[2023-07-20][08:49:56][ERROR][app] 	/private/var/tmp/_bazel_ec2-user/58ad2e50dcfb9c20da085cd0810f895a/sandbox/darwin-sandbox/5637/execroot/__main__/enterprise/cmd/sourcegraph/main.go:50 +0x118
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 224 [select]:
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume(0x140021c7530)
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:59 +0xa8
[2023-07-20][08:49:56][ERROR][app] created by github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).start
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:51 +0x60
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 10 [select]:
[2023-07-20][08:49:56][ERROR][app] go.opencensus.io/stats/view.(*worker).start(0x1400033c280)
[2023-07-20][08:49:56][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:292 +0x88
[2023-07-20][08:49:56][ERROR][app] created by go.opencensus.io/stats/view.init.0
[2023-07-20][08:49:56][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:34 +0xa4
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 225 [select, 4 minutes]:
[2023-07-20][08:49:56][ERROR][app] io.(*pipe).read(0x14002184c60, {0x140023a96b6, 0x94a, 0x0?})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/io/pipe.go:57 +0x84
[2023-07-20][08:49:56][ERROR][app] io.(*PipeReader).Read(0x5000?, {0x140023a96b6?, 0x9a3?, 0x113344500?})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/io/pipe.go:136 +0x24
[2023-07-20][08:49:56][ERROR][app] bufio.(*Scanner).Scan(0x14001cfbf48)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/bufio/scan.go:214 +0x908
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter.func1()
[2023-07-20][08:49:56][ERROR][app] 	internal/singleprogram/postgresql.go:186 +0xb0
[2023-07-20][08:49:56][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter
[2023-07-20][08:49:56][ERROR][app] 	internal/singleprogram/postgresql.go:184 +0x1dc
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 126 [select, 5 minutes]:
[2023-07-20][08:49:56][ERROR][app] github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do(0x1400100bba8, 0x20)
[2023-07-20][08:49:56][ERROR][app] 	internal/limiter/mutable.go:94 +0x14c
[2023-07-20][08:49:56][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/limiter.NewMutable
[2023-07-20][08:49:56][ERROR][app] 	internal/limiter/mutable.go:38 +0x108
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 266 [syscall, 4 minutes]:
[2023-07-20][08:49:56][ERROR][app] syscall.syscall6(0x113344a68?, 0x10209af17?, 0x1400054d608?, 0x10209acf8?, 0x9000010101d5a8?, 0x11ad0d218?, 0x113344a68?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/runtime/sys_darwin.go:45 +0x64
[2023-07-20][08:49:56][ERROR][app] syscall.wait4(0x1400054d608?, 0x1021446c8?, 0x90?, 0x10f1a5380?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/syscall/zsyscall_darwin_arm64.go:43 +0x4c
[2023-07-20][08:49:56][ERROR][app] syscall.Wait4(0x14000300900?, 0x140000b5e44, 0x1057a5a95?, 0x1400054d688?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/syscall/syscall_bsd.go:144 +0x28
[2023-07-20][08:49:56][ERROR][app] os.(*Process).wait(0x140014369c0)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec_unix.go:43 +0x80
[2023-07-20][08:49:56][ERROR][app] os.(*Process).Wait(...)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec.go:132
[2023-07-20][08:49:56][ERROR][app] os/exec.(*Cmd).Wait(0x14001b6c2c0)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:599 +0x3c
[2023-07-20][08:49:56][ERROR][app] github.com/fergusstrange/embedded-postgres.startPostgres.func1()
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/embedded_postgres.go:230 +0x74
[2023-07-20][08:49:56][ERROR][app] created by github.com/fergusstrange/embedded-postgres.startPostgres
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/embedded_postgres.go:228 +0x298
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 277 [chan receive]:
[2023-07-20][08:49:56][ERROR][app] github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_golang_glog/glog.go:882 +0x5c
[2023-07-20][08:49:56][ERROR][app] created by github.com/golang/glog.init.0
[2023-07-20][08:49:56][ERROR][app] 	external/com_github_golang_glog/glog.go:410 +0x200
[2023-07-20][08:49:56][ERROR][app] 
[2023-07-20][08:49:56][ERROR][app] goroutine 49 [IO wait, 4 minutes]:
[2023-07-20][08:49:56][ERROR][app] internal/poll.runtime_pollWait(0x11ac284b8, 0x72)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/runtime/netpoll.go:305 +0xa0
[2023-07-20][08:49:56][ERROR][app] internal/poll.(*pollDesc).wait(0x14002184420?, 0x1400112a200?, 0x1)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
[2023-07-20][08:49:56][ERROR][app] internal/poll.(*pollDesc).waitRead(...)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:89
[2023-07-20][08:49:56][ERROR][app] internal/poll.(*FD).Read(0x14002184420, {0x1400112a200, 0x200, 0x200})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
[2023-07-20][08:49:56][ERROR][app] os.(*File).read(...)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/file_posix.go:31
[2023-07-20][08:49:56][ERROR][app] os.(*File).Read(0x14001c3ab70, {0x1400112a200?, 0x140000a4678?, 0x10209b6d0?})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/file.go:119 +0x5c
[2023-07-20][08:49:56][ERROR][app] bytes.(*Buffer).ReadFrom(0x1400233aae0, {0x10f2e0780, 0x14001c3ab70})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/bytes/buffer.go:202 +0x90
[2023-07-20][08:49:56][ERROR][app] io.copyBuffer({0x10f2cd9a0, 0x1400233aae0}, {0x10f2e0780, 0x14001c3ab70}, {0x0, 0x0, 0x0})
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/io/io.go:413 +0x108
[2023-07-20][08:49:56][ERROR][app] io.Copy(...)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/io/io.go:386
[2023-07-20][08:49:56][ERROR][app] os/exec.(*Cmd).writerDescriptor.func1()
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:407 +0x44
[2023-07-20][08:49:56][ERROR][app] os/exec.(*Cmd).Start.func1(0x14000003380?)
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:544 +0x2c
[2023-07-20][08:49:56][ERROR][app] created by os/exec.(*Cmd).Start
[2023-07-20][08:49:56][ERROR][app] 	GOROOT/src/os/exec/exec.go:543 +0x5d0
[2023-07-20][08:49:56][ERROR][app] Cody app backend terminated with exit code 2

`
