### ISSUE TITLE
I can't open the desktop APP on Mac

### ISSUE THREAD

**Issue by javierbotero** [sourcegraph/app#56]
I donwloaded the intel version for mac, I am in a Macbook pro 2016 intel core i7, OS macOS Big Sur. v 11.6.

```
[2023-08-09][02:29:04][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin amd64
[2023-08-09][02:34:04][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 291 [running]:
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0xc000646228?)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/conf/store.go:175 +0x2c8
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0xc0012f39e0)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/conf/store.go:137 +0x2f
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0xc0006b8d00, 0x10b113fd0)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/conf/client.go:169 +0x11e
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0xc001d65ce0?)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/conf/client.go:136 +0x28
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/cmd/symbols/parser/config.go:52 +0x25
[2023-08-09][02:34:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/cmd/symbols/parser/config.go:51 +0xb1
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 1 [sync.Cond.Wait]:
[2023-08-09][02:34:04][ERROR][app] sync.runtime_notifyListWait(0xc001e7a348, 0x1003)
[2023-08-09][02:34:04][ERROR][app] 	runtime/sema.go:517 +0x14c
[2023-08-09][02:34:04][ERROR][app] sync.(*Cond).Wait(0xd?)
[2023-08-09][02:34:04][ERROR][app] 	sync/cond.go:70 +0x8c
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2pipe).Read(0xc001e7a330, {0xc006db8f64, 0x3c309c, 0x3c309c})
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:3668 +0xeb
[2023-08-09][02:34:04][ERROR][app] net/http.http2transportResponseBody.Read({0xc001e7a300?}, {0xc006db8f64?, 0x4ee000?, 0x4ee000?})
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:9157 +0x85
[2023-08-09][02:34:04][ERROR][app] io.ReadAll({0x13927adf8, 0xc001e7a300})
[2023-08-09][02:34:04][ERROR][app] 	io/io.go:661 +0xfe
[2023-08-09][02:34:04][ERROR][app] io/ioutil.ReadAll(...)
[2023-08-09][02:34:04][ERROR][app] 	io/ioutil/ioutil.go:27
[2023-08-09][02:34:04][ERROR][app] github.com/fergusstrange/embedded-postgres.defaultRemoteFetchStrategy.func1()
[2023-08-09][02:34:04][ERROR][app] 	github.com/fergusstrange/embedded-postgres@v1.19.0/remote_fetch.go:48 +0x288
[2023-08-09][02:34:04][ERROR][app] github.com/fergusstrange/embedded-postgres.(*EmbeddedPostgres).Start(0xc00015b770)
[2023-08-09][02:34:04][ERROR][app] 	github.com/fergusstrange/embedded-postgres@v1.19.0/embedded_postgres.go:100 +0x313
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.startEmbeddedPostgreSQL({0x10c759590, 0xc001fc4c00}, {0xc0006da870, 0x49})
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/singleprogram/postgresql.go:144 +0x795
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.initPostgreSQL({0x10c759590, 0xc001fc4c00}, {0xc0006da870?, 0x12?})
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/singleprogram/postgresql.go:39 +0x53
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.Init({0x10c759590, 0xc001fc4c00})
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/singleprogram/singleprogram.go:106 +0xb46
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main.func3(0xc001e8f680?)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/service/svcmain/svcmain.go:91 +0xa7
[2023-08-09][02:34:04][ERROR][app] github.com/urfave/cli/v2.(*Command).Run(0xc001e8f680, 0xc001fc4800, {0xc000180050, 0x5, 0x5})
[2023-08-09][02:34:04][ERROR][app] 	github.com/urfave/cli/v2@v2.23.7/command.go:271 +0xa42
[2023-08-09][02:34:04][ERROR][app] github.com/urfave/cli/v2.(*App).RunContext(0xc0005c7860, {0x10c73bc98?, 0xc00019e008}, {0xc000180050, 0x5, 0x5})
[2023-08-09][02:34:04][ERROR][app] 	github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x665
[2023-08-09][02:34:04][ERROR][app] github.com/urfave/cli/v2.(*App).Run(...)
[2023-08-09][02:34:04][ERROR][app] 	github.com/urfave/cli/v2@v2.23.7/app.go:310
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main({0x10f277980, 0xd, 0xd}, {0xf9?, 0x0?}, {0xc000180050?, 0x5, 0x5})
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/service/svcmain/svcmain.go:102 +0x6b6
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd.MainEnterprise(...)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go:15
[2023-08-09][02:34:04][ERROR][app] main.main()
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/main.go:50 +0xd4
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 28 [select]:
[2023-08-09][02:34:04][ERROR][app] go.opencensus.io/stats/view.(*worker).start(0xc00011ab80)
[2023-08-09][02:34:04][ERROR][app] 	go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
[2023-08-09][02:34:04][ERROR][app] created by go.opencensus.io/stats/view.init.0
[2023-08-09][02:34:04][ERROR][app] 	go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 123 [select, 5 minutes]:
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do(0xc0006a1398, 0x20)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/limiter/mutable.go:94 +0x1bd
[2023-08-09][02:34:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/limiter.NewMutable
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/limiter/mutable.go:38 +0x105
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 246 [chan receive]:
[2023-08-09][02:34:04][ERROR][app] github.com/golang/glog.(*loggingT).flushDaemon(0xc00103d080?)
[2023-08-09][02:34:04][ERROR][app] 	github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
[2023-08-09][02:34:04][ERROR][app] created by github.com/golang/glog.init.0
[2023-08-09][02:34:04][ERROR][app] 	github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 269 [IO wait]:
[2023-08-09][02:34:04][ERROR][app] internal/poll.runtime_pollWait(0x1391d5670, 0x72)
[2023-08-09][02:34:04][ERROR][app] 	runtime/netpoll.go:305 +0x89
[2023-08-09][02:34:04][ERROR][app] internal/poll.(*pollDesc).wait(0xc000aee300?, 0xc001e36000?, 0x0)
[2023-08-09][02:34:04][ERROR][app] 	internal/poll/fd_poll_runtime.go:84 +0x32
[2023-08-09][02:34:04][ERROR][app] internal/poll.(*pollDesc).waitRead(...)
[2023-08-09][02:34:04][ERROR][app] 	internal/poll/fd_poll_runtime.go:89
[2023-08-09][02:34:04][ERROR][app] internal/poll.(*FD).Read(0xc000aee300, {0xc001e36000, 0xa000, 0xa000})
[2023-08-09][02:34:04][ERROR][app] 	internal/poll/fd_unix.go:167 +0x25a
[2023-08-09][02:34:04][ERROR][app] net.(*netFD).Read(0xc000aee300, {0xc001e36000?, 0x10024c7a2?, 0xc001f53880?})
[2023-08-09][02:34:04][ERROR][app] 	net/fd_posix.go:55 +0x29
[2023-08-09][02:34:04][ERROR][app] net.(*conn).Read(0xc00019b1d8, {0xc001e36000?, 0xd?, 0xc001f53880?})
[2023-08-09][02:34:04][ERROR][app] 	net/net.go:183 +0x45
[2023-08-09][02:34:04][ERROR][app] crypto/tls.(*atLeastReader).Read(0xc00048fb60, {0xc001e36000?, 0x0?, 0x100114c8f?})
[2023-08-09][02:34:04][ERROR][app] 	crypto/tls/conn.go:787 +0x3d
[2023-08-09][02:34:04][ERROR][app] bytes.(*Buffer).ReadFrom(0xc001a47af8, {0x10c6ee0a0, 0xc00048fb60})
[2023-08-09][02:34:04][ERROR][app] 	bytes/buffer.go:202 +0x98
[2023-08-09][02:34:04][ERROR][app] crypto/tls.(*Conn).readFromUntil(0xc001a47880, {0x1391d5c40?, 0xc00019b1d8}, 0xc001e37f27?)
[2023-08-09][02:34:04][ERROR][app] 	crypto/tls/conn.go:809 +0xe5
[2023-08-09][02:34:04][ERROR][app] crypto/tls.(*Conn).readRecordOrCCS(0xc001a47880, 0x0)
[2023-08-09][02:34:04][ERROR][app] 	crypto/tls/conn.go:616 +0x116
[2023-08-09][02:34:04][ERROR][app] crypto/tls.(*Conn).readRecord(...)
[2023-08-09][02:34:04][ERROR][app] 	crypto/tls/conn.go:582
[2023-08-09][02:34:04][ERROR][app] crypto/tls.(*Conn).Read(0xc001a47880, {0xc001a74000, 0x1000, 0xc001a07cb0?})
[2023-08-09][02:34:04][ERROR][app] 	crypto/tls/conn.go:1315 +0x16f
[2023-08-09][02:34:04][ERROR][app] bufio.(*Reader).Read(0xc0019f0240, {0xc001a72120, 0x9, 0xf1b?})
[2023-08-09][02:34:04][ERROR][app] 	bufio/bufio.go:237 +0x1bb
[2023-08-09][02:34:04][ERROR][app] io.ReadAtLeast({0x10c6eaa80, 0xc0019f0240}, {0xc001a72120, 0x9, 0x9}, 0x9)
[2023-08-09][02:34:04][ERROR][app] 	io/io.go:332 +0x9a
[2023-08-09][02:34:04][ERROR][app] io.ReadFull(...)
[2023-08-09][02:34:04][ERROR][app] 	io/io.go:351
[2023-08-09][02:34:04][ERROR][app] net/http.http2readFrameHeader({0xc001a72120?, 0x9?, 0xc001c09ef0?}, {0x10c6eaa80?, 0xc0019f0240?})
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:1565 +0x6e
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2Framer).ReadFrame(0xc001a720e0)
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:1829 +0x95
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2clientConnReadLoop).run(0xc001a07f98)
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:8874 +0x130
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2ClientConn).readLoop(0xc0002f7080)
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:8770 +0x6f
[2023-08-09][02:34:04][ERROR][app] created by net/http.(*http2Transport).newClientConn
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:7477 +0xaaa
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 295 [select, 5 minutes]:
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2clientStream).writeRequest(0xc001e7a300, 0xc001c0aa00)
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:8095 +0x9c7
[2023-08-09][02:34:04][ERROR][app] net/http.(*http2clientStream).doRequest(0x1005ae28a?, 0xc001ef4d80?)
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:7957 +0x1e
[2023-08-09][02:34:04][ERROR][app] created by net/http.(*http2ClientConn).RoundTrip
[2023-08-09][02:34:04][ERROR][app] 	net/http/h2_bundle.go:7886 +0x30a
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 281 [select]:
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume(0xc0010575f0)
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/log@v0.0.0-20230711093019-40c57b632cca/internal/sinkcores/sentrycore/worker.go:59 +0xd7
[2023-08-09][02:34:04][ERROR][app] created by github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).start
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/log@v0.0.0-20230711093019-40c57b632cca/internal/sinkcores/sentrycore/worker.go:51 +0x56
[2023-08-09][02:34:04][ERROR][app] 
[2023-08-09][02:34:04][ERROR][app] goroutine 282 [select, 5 minutes]:
[2023-08-09][02:34:04][ERROR][app] io.(*pipe).read(0xc00103dda0, {0xc001274000, 0x1000, 0x1?})
[2023-08-09][02:34:04][ERROR][app] 	io/pipe.go:57 +0xb1
[2023-08-09][02:34:04][ERROR][app] io.(*PipeReader).Read(0x0?, {0xc001274000?, 0x0?, 0x0?})
[2023-08-09][02:34:04][ERROR][app] 	io/pipe.go:136 +0x25
[2023-08-09][02:34:04][ERROR][app] bufio.(*Scanner).Scan(0xc0000bcf50)
[2023-08-09][02:34:04][ERROR][app] 	bufio/scan.go:214 +0x876
[2023-08-09][02:34:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter.func1()
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/singleprogram/postgresql.go:186 +0xda
[2023-08-09][02:34:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter
[2023-08-09][02:34:04][ERROR][app] 	github.com/sourcegraph/sourcegraph/internal/singleprogram/postgresql.go:184 +0x1c5
[2023-08-09][02:34:04][ERROR][app] Cody app backend terminated with exit code 2
[2023-08-09][02:39:56][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin amd64
[2023-08-09][02:40:41][ERROR][app] [31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m| Docker is unavailable                                                        |[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m Sourcegraph is better when Docker is available; some features may not work:  [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m - Batch changes                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m - Symbol search                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m - Symbols overview tab (on repository pages)                                 [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m| src-cli is unavailable                                                       |[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m Sourcegraph is better when src-cli is available; batch changes may not work. [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m Installation: https://github.com/sourcegraph/src-cli                         [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[2023-08-09][02:40:41][ERROR][app] [0m[31;43;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:41][ERROR][app] [0m1691548841613386000	WARN	servegit	servegit/service.go:62	github.com/sourcegraph/sourcegraph/internal/service/servegit.(*svc).Start	skipping local code since the environment variable SRC is not set	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {}}
[2023-08-09][02:40:41][ERROR][app] 1691548841630565000	ERROR	service	run/util.go:44	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get src-cli version	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"error": "'src version -client-only': : exec: \"src\": executable file not found in $PATH"}}
[2023-08-09][02:40:41][ERROR][app] 1691548841630565000	ERROR	service	run/util.go:44	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get src-cli version	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"error": "'src version -client-only': : exec: \"src\": executable file not found in $PATH"}}
[2023-08-09][02:40:41][ERROR][app] 1691548841772920000	ERROR	service	run/util.go:49	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get docker version	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"error": "'docker version -f {{.Server.Version}}': Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n: exit status 1"}}
[2023-08-09][02:40:41][ERROR][app] 1691548841772917000	ERROR	service	run/util.go:49	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get docker version	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"error": "'docker version -f {{.Server.Version}}': Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n: exit status 1"}}
[2023-08-09][02:40:45][ERROR][app] 1691548845850669000	WARN	frontend.SecurityEvents	audit/audit.go:51	github.com/sourcegraph/sourcegraph/internal/audit.Log	AccountCreated (sampling immunity token: 2c5851f9-c00c-4699-ab37-940037df8016)	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"audit": {"auditId": "2c5851f9-c00c-4699-ab37-940037df8016", "entity": "security events", "actor": {"actorUID": "unknown", "ip": "unknown", "userAgent": "unknown", "X-Forwarded-For": "unknown"}}, "event": {"URL": "", "UserID": 1, "AnonymousUserID": "", "source": "BACKEND", "argument": "{\"creator\":0,\"site_admin\":true,\"service_type\":\"\"}", "version": "2023.7.11+1384.7d20a90ce7", "timestamp": "2023-08-09 02:40:45.850187 +0000 UTC"}}}
[2023-08-09][02:40:45][ERROR][app] tauri:sign-in-url: http://localhost:3080/sign-in?s=6iPxMcdiU4v2-E9nIZb5kJvo7ca5yZe8n3sAYrHoUkA%3D
[2023-08-09][02:40:45][ERROR][app] [30;42;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:45][ERROR][app] [0m[30;42;1m|                                                                              |[0m
[2023-08-09][02:40:45][ERROR][app] [0m[30;42;1m| Sourcegraph is now available on http://localhost:3080                        |[0m
[2023-08-09][02:40:45][ERROR][app] [0m[30;42;1m|                                                                              |[0m
[2023-08-09][02:40:45][ERROR][app] [0m[30;42;1m|------------------------------------------------------------------------------|[0m
[2023-08-09][02:40:45][ERROR][app] [0m1691548845908020000	WARN	service.worker	runtime/runtime.go:125	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/worker/runtime.New	runtime 'docker' is not supported: missing required tools	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"dockerTools": ["src"]}}
[2023-08-09][02:40:45][ERROR][app] 1691548845908068000	WARN	executor	singlebinary/service.go:40	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/singlebinary.svc.Start.func1	executor for other queue failed	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"error": "runtime is not configured"}}
[2023-08-09][02:40:45][ERROR][app] 1691548845977889000	WARN	licensing.licenseChecker	licensing/check.go:100	github.com/sourcegraph/sourcegraph/internal/licensing.(*licenseChecker).Handle	invalid http response while checking license validity	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"httpStatus": "401 Unauthorized", "siteID": "a2ce3344-99a5-4493-8b3d-4898f156d690"}}
[2023-08-09][02:40:45][ERROR][app] 1691548845978378000	ERROR	licensing.check-license-validity	goroutine/periodic.go:95	github.com/sourcegraph/sourcegraph/internal/goroutine.(*simpleHandler).HandleError	An error occurred in a background task	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"handler": "licensing.check-license-validity", "error": "Failed to check license, status code: 401"}}
[2023-08-09][02:40:46][ERROR][app] 1691548846495724000	WARN	service.worker	runtime/runtime.go:125	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/worker/runtime.New	runtime 'docker' is not supported: missing required tools	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"dockerTools": ["src"]}}
[2023-08-09][02:40:46][ERROR][app] 1691548846496224000	WARN	sourcegraph	svcmain/svcmain.go:261	github.com/sourcegraph/sourcegraph/internal/service/svcmain.run.func1	failed to start service (skipping)	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.7.11+1384.7d20a90ce7", "service.instance.id": "Javiers-MacBook-Pro.local"}, "Attributes": {"service": "executor", "error": "runtime is not configured"}}

```

**Comment by chris-wickens** [comment]
I was running into a similar problem. Updating and restarting Docker Desktop, then restarting Cody twice including a data wipe resolved it for me.

**Comment by maxim-saplin** [comment]
Same for me, though on M1 Mac (macOS 13.5, Docker Desktop 4.21.1)

<img width="683" alt="image" src="https://github.com/sourcegraph/app/assets/7947027/5e240d9c-b262-407c-94ff-7d1dd950c893">

[Cody.log.zip](https://github.com/sourcegraph/app/files/12313936/Cody.log.zip)
