### ISSUE TITLE
Start failed !!!

### ISSUE THREAD

**Issue by jepack** [sourcegraph/app#57]
[2023-08-11][08:42:04][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin arm64
[2023-08-11][08:47:04][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 281 [running]:
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0x1400011cfb8?)
[2023-08-11][08:47:04][ERROR][app] 	internal/conf/store.go:175 +0x300
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0x14000a8f0e0)
[2023-08-11][08:47:04][ERROR][app] 	internal/conf/store.go:137 +0x2c
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0x14000d99dc0, 0x10f8c2070)
[2023-08-11][08:47:04][ERROR][app] 	internal/conf/client.go:169 +0x1b8
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x14001e9e870?)
[2023-08-11][08:47:04][ERROR][app] 	internal/conf/client.go:136 +0x28
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-08-11][08:47:04][ERROR][app] 	cmd/symbols/parser/config.go:52 +0x24
[2023-08-11][08:47:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-08-11][08:47:04][ERROR][app] 	cmd/symbols/parser/config.go:51 +0xe8
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 1 [sync.Cond.Wait]:
[2023-08-11][08:47:04][ERROR][app] sync.runtime_notifyListWait(0x14001a08048, 0x157c)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/runtime/sema.go:517 +0x16c
[2023-08-11][08:47:04][ERROR][app] sync.(*Cond).Wait(0x14001a08038)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/sync/cond.go:70 +0xd0
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2pipe).Read(0x14001a08030, {0x1400671cd9d, 0x57263, 0x57263})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:3668 +0x130
[2023-08-11][08:47:04][ERROR][app] net/http.http2transportResponseBody.Read({0x14001a08000?}, {0x1400671cd9d?, 0x3f2000?, 0x3f2000?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:9157 +0x54
[2023-08-11][08:47:04][ERROR][app] io.ReadAll({0x13b15aa88, 0x14001a08000})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/io.go:661 +0xe4
[2023-08-11][08:47:04][ERROR][app] io/ioutil.ReadAll(...)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/ioutil/ioutil.go:27
[2023-08-11][08:47:04][ERROR][app] github.com/fergusstrange/embedded-postgres.defaultRemoteFetchStrategy.func1()
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/remote_fetch.go:48 +0x1d8
[2023-08-11][08:47:04][ERROR][app] github.com/fergusstrange/embedded-postgres.(*EmbeddedPostgres).Start(0x140002332c0)
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/embedded_postgres.go:100 +0x264
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.startEmbeddedPostgreSQL({0x10f943970, 0x14001f66cc0}, {0x14000a6bf40, 0x49})
[2023-08-11][08:47:04][ERROR][app] 	internal/singleprogram/postgresql.go:144 +0x57c
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.initPostgreSQL({0x10f943970, 0x14001f66cc0}, {0x14000a6bf40?, 0x12?})
[2023-08-11][08:47:04][ERROR][app] 	internal/singleprogram/postgresql.go:39 +0x40
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.Init({0x10f943970, 0x14001f66cc0})
[2023-08-11][08:47:04][ERROR][app] 	internal/singleprogram/singleprogram.go:106 +0x888
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main.func3(0x14001d57e00?)
[2023-08-11][08:47:04][ERROR][app] 	internal/service/svcmain/svcmain.go:91 +0x80
[2023-08-11][08:47:04][ERROR][app] github.com/urfave/cli/v2.(*Command).Run(0x14001d57e00, 0x14001f66900, {0x140000700a0, 0x5, 0x5})
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_urfave_cli_v2/command.go:271 +0x78c
[2023-08-11][08:47:04][ERROR][app] github.com/urfave/cli/v2.(*App).RunContext(0x14001f72000, {0x10f926778?, 0x14000076078}, {0x140000700a0, 0x5, 0x5})
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:333 +0x5a4
[2023-08-11][08:47:04][ERROR][app] github.com/urfave/cli/v2.(*App).Run(...)
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:310
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main({0x1120c6ec0, 0xd, 0xd}, {0x64?, 0x0?}, {0x140000700a0?, 0x5, 0x5})
[2023-08-11][08:47:04][ERROR][app] 	internal/service/svcmain/svcmain.go:102 +0x620
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd.MainEnterprise(...)
[2023-08-11][08:47:04][ERROR][app] 	enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go:15
[2023-08-11][08:47:04][ERROR][app] main.main()
[2023-08-11][08:47:04][ERROR][app] 	/private/var/tmp/_bazel_ec2-user/58ad2e50dcfb9c20da085cd0810f895a/sandbox/darwin-sandbox/5637/execroot/__main__/enterprise/cmd/sourcegraph/main.go:50 +0x118
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 12 [select]:
[2023-08-11][08:47:04][ERROR][app] go.opencensus.io/stats/view.(*worker).start(0x1400012e880)
[2023-08-11][08:47:04][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:292 +0x88
[2023-08-11][08:47:04][ERROR][app] created by go.opencensus.io/stats/view.init.0
[2023-08-11][08:47:04][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:34 +0xa4
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 287 [select, 5 minutes]:
[2023-08-11][08:47:04][ERROR][app] io.(*pipe).read(0x14001f138c0, {0x14002450000, 0x1000, 0x1026d9100?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/pipe.go:57 +0x84
[2023-08-11][08:47:04][ERROR][app] io.(*PipeReader).Read(0x1400199dd68?, {0x14002450000?, 0x140000021a0?, 0x4?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/pipe.go:136 +0x24
[2023-08-11][08:47:04][ERROR][app] bufio.(*Scanner).Scan(0x1400199df48)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/bufio/scan.go:214 +0x908
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter.func1()
[2023-08-11][08:47:04][ERROR][app] 	internal/singleprogram/postgresql.go:186 +0xb0
[2023-08-11][08:47:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter
[2023-08-11][08:47:04][ERROR][app] 	internal/singleprogram/postgresql.go:184 +0x1dc
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 286 [select]:
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume(0x14001f1b860)
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:59 +0xa8
[2023-08-11][08:47:04][ERROR][app] created by github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).start
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:51 +0x60
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 137 [select, 5 minutes]:
[2023-08-11][08:47:04][ERROR][app] github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do(0x14001d7a060, 0x20)
[2023-08-11][08:47:04][ERROR][app] 	internal/limiter/mutable.go:94 +0x14c
[2023-08-11][08:47:04][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/limiter.NewMutable
[2023-08-11][08:47:04][ERROR][app] 	internal/limiter/mutable.go:38 +0x108
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 254 [chan receive]:
[2023-08-11][08:47:04][ERROR][app] github.com/golang/glog.(*loggingT).flushDaemon(0x1400182fa70?)
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_golang_glog/glog.go:882 +0x5c
[2023-08-11][08:47:04][ERROR][app] created by github.com/golang/glog.init.0
[2023-08-11][08:47:04][ERROR][app] 	external/com_github_golang_glog/glog.go:410 +0x200
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 327 [select, 5 minutes]:
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2clientStream).writeRequest(0x14001a08000, 0x14001b8d400)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8095 +0x7d4
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2clientStream).doRequest(0x14001c97440?, 0x14001f42790?)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7957 +0x20
[2023-08-11][08:47:04][ERROR][app] created by net/http.(*http2ClientConn).RoundTrip
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7886 +0x2ec
[2023-08-11][08:47:04][ERROR][app] 
[2023-08-11][08:47:04][ERROR][app] goroutine 326 [IO wait]:
[2023-08-11][08:47:04][ERROR][app] internal/poll.runtime_pollWait(0x13b530e58, 0x72)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/runtime/netpoll.go:305 +0xa0
[2023-08-11][08:47:04][ERROR][app] internal/poll.(*pollDesc).wait(0x14001d49880?, 0x140004e9900?, 0x0)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
[2023-08-11][08:47:04][ERROR][app] internal/poll.(*pollDesc).waitRead(...)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:89
[2023-08-11][08:47:04][ERROR][app] internal/poll.(*FD).Read(0x14001d49880, {0x140004e9900, 0x1300, 0x1300})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
[2023-08-11][08:47:04][ERROR][app] net.(*netFD).Read(0x14001d49880, {0x140004e9900?, 0x140004e9e95?, 0x6?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/fd_posix.go:55 +0x28
[2023-08-11][08:47:04][ERROR][app] net.(*conn).Read(0x14000010b80, {0x140004e9900?, 0x8?, 0x12fb?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/net.go:183 +0x34
[2023-08-11][08:47:04][ERROR][app] crypto/tls.(*atLeastReader).Read(0x1400217dd88, {0x140004e9900?, 0x0?, 0x1028aa328?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:787 +0x40
[2023-08-11][08:47:04][ERROR][app] bytes.(*Buffer).ReadFrom(0x140002eb778, {0x10f8d8f00, 0x1400217dd88})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/bytes/buffer.go:202 +0x90
[2023-08-11][08:47:04][ERROR][app] crypto/tls.(*Conn).readFromUntil(0x140002eb500, {0x13b15aa68?, 0x14000010b80}, 0xd70?)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:809 +0xd4
[2023-08-11][08:47:04][ERROR][app] crypto/tls.(*Conn).readRecordOrCCS(0x140002eb500, 0x0)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:616 +0xd8
[2023-08-11][08:47:04][ERROR][app] crypto/tls.(*Conn).readRecord(...)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:582
[2023-08-11][08:47:04][ERROR][app] crypto/tls.(*Conn).Read(0x140002eb500, {0x14001a07000, 0x1000, 0x10f52cfc0?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:1315 +0x178
[2023-08-11][08:47:04][ERROR][app] bufio.(*Reader).Read(0x14001a04240, {0x1400246656a, 0x573, 0x9?})
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/bufio/bufio.go:237 +0x1e0
[2023-08-11][08:47:04][ERROR][app] io.ReadAtLeast({0x10f8d58e0, 0x14001a04240}, {0x14002466000, 0xadd, 0x4000}, 0xadd)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/io.go:332 +0xa0
[2023-08-11][08:47:04][ERROR][app] io.ReadFull(...)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/io/io.go:351
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2Framer).ReadFrame(0x140010d0b60)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:1837 +0x10c
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2clientConnReadLoop).run(0x1400059af88)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8874 +0xfc
[2023-08-11][08:47:04][ERROR][app] net/http.(*http2ClientConn).readLoop(0x14001c7fe00)
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8770 +0x5c
[2023-08-11][08:47:04][ERROR][app] created by net/http.(*http2Transport).newClientConn
[2023-08-11][08:47:04][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7477 +0x920
[2023-08-11][08:47:04][ERROR][app] Cody app backend terminated with exit code 2
[2023-08-11][08:47:19][ERROR][app::common] No such file or directory (os error 2)
[2023-08-11][08:47:20][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin arm64
[2023-08-11][08:52:20][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 296 [running]:
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0x140013203b0?)
[2023-08-11][08:52:20][ERROR][app] 	internal/conf/store.go:175 +0x300
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0x14001020900)
[2023-08-11][08:52:20][ERROR][app] 	internal/conf/store.go:137 +0x2c
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0x14000eacc80, 0x1100ba070)
[2023-08-11][08:52:20][ERROR][app] 	internal/conf/client.go:169 +0x1b8
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x14001061200?)
[2023-08-11][08:52:20][ERROR][app] 	internal/conf/client.go:136 +0x28
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-08-11][08:52:20][ERROR][app] 	cmd/symbols/parser/config.go:52 +0x24
[2023-08-11][08:52:20][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-08-11][08:52:20][ERROR][app] 	cmd/symbols/parser/config.go:51 +0xe8
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 1 [sync.Cond.Wait]:
[2023-08-11][08:52:20][ERROR][app] sync.runtime_notifyListWait(0x14001d7d0c8, 0x17b8)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/runtime/sema.go:517 +0x16c
[2023-08-11][08:52:20][ERROR][app] sync.(*Cond).Wait(0x14001d7d0b8)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/sync/cond.go:70 +0xd0
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2pipe).Read(0x14001d7d0b0, {0x14003e40998, 0x35f668, 0x35f668})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:3668 +0x130
[2023-08-11][08:52:20][ERROR][app] net/http.http2transportResponseBody.Read({0x14001d7d080?}, {0x14003e40998?, 0x4ee000?, 0x4ee000?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:9157 +0x54
[2023-08-11][08:52:20][ERROR][app] io.ReadAll({0x13bce5578, 0x14001d7d080})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/io.go:661 +0xe4
[2023-08-11][08:52:20][ERROR][app] io/ioutil.ReadAll(...)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/ioutil/ioutil.go:27
[2023-08-11][08:52:20][ERROR][app] github.com/fergusstrange/embedded-postgres.defaultRemoteFetchStrategy.func1()
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/remote_fetch.go:48 +0x1d8
[2023-08-11][08:52:20][ERROR][app] github.com/fergusstrange/embedded-postgres.(*EmbeddedPostgres).Start(0x140002933b0)
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/embedded_postgres.go:100 +0x264
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.startEmbeddedPostgreSQL({0x11013b970, 0x14001a50940}, {0x1400007d860, 0x49})
[2023-08-11][08:52:20][ERROR][app] 	internal/singleprogram/postgresql.go:144 +0x57c
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.initPostgreSQL({0x11013b970, 0x14001a50940}, {0x1400007d860?, 0x12?})
[2023-08-11][08:52:20][ERROR][app] 	internal/singleprogram/postgresql.go:39 +0x40
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.Init({0x11013b970, 0x14001a50940})
[2023-08-11][08:52:20][ERROR][app] 	internal/singleprogram/singleprogram.go:106 +0x888
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main.func3(0x14002239180?)
[2023-08-11][08:52:20][ERROR][app] 	internal/service/svcmain/svcmain.go:91 +0x80
[2023-08-11][08:52:20][ERROR][app] github.com/urfave/cli/v2.(*Command).Run(0x14002239180, 0x14001a50580, {0x1400018e050, 0x5, 0x5})
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_urfave_cli_v2/command.go:271 +0x78c
[2023-08-11][08:52:20][ERROR][app] github.com/urfave/cli/v2.(*App).RunContext(0x14000534d20, {0x11011e778?, 0x140001a6008}, {0x1400018e050, 0x5, 0x5})
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:333 +0x5a4
[2023-08-11][08:52:20][ERROR][app] github.com/urfave/cli/v2.(*App).Run(...)
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:310
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main({0x1128beec0, 0xd, 0xd}, {0x64?, 0x0?}, {0x1400018e050?, 0x5, 0x5})
[2023-08-11][08:52:20][ERROR][app] 	internal/service/svcmain/svcmain.go:102 +0x620
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd.MainEnterprise(...)
[2023-08-11][08:52:20][ERROR][app] 	enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go:15
[2023-08-11][08:52:20][ERROR][app] main.main()
[2023-08-11][08:52:20][ERROR][app] 	/private/var/tmp/_bazel_ec2-user/58ad2e50dcfb9c20da085cd0810f895a/sandbox/darwin-sandbox/5637/execroot/__main__/enterprise/cmd/sourcegraph/main.go:50 +0x118
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 40 [select]:
[2023-08-11][08:52:20][ERROR][app] go.opencensus.io/stats/view.(*worker).start(0x14000368b00)
[2023-08-11][08:52:20][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:292 +0x88
[2023-08-11][08:52:20][ERROR][app] created by go.opencensus.io/stats/view.init.0
[2023-08-11][08:52:20][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:34 +0xa4
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 136 [select, 5 minutes]:
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do(0x14001c44ff0, 0x20)
[2023-08-11][08:52:20][ERROR][app] 	internal/limiter/mutable.go:94 +0x14c
[2023-08-11][08:52:20][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/limiter.NewMutable
[2023-08-11][08:52:20][ERROR][app] 	internal/limiter/mutable.go:38 +0x108
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 266 [chan receive]:
[2023-08-11][08:52:20][ERROR][app] github.com/golang/glog.(*loggingT).flushDaemon(0x140013387e0?)
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_golang_glog/glog.go:882 +0x5c
[2023-08-11][08:52:20][ERROR][app] created by github.com/golang/glog.init.0
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_golang_glog/glog.go:410 +0x200
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 301 [select]:
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume(0x1400224f2f0)
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:59 +0xa8
[2023-08-11][08:52:20][ERROR][app] created by github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).start
[2023-08-11][08:52:20][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:51 +0x60
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 302 [select, 5 minutes]:
[2023-08-11][08:52:20][ERROR][app] io.(*pipe).read(0x1400222f020, {0x14001c98000, 0x1000, 0x0?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/pipe.go:57 +0x84
[2023-08-11][08:52:20][ERROR][app] io.(*PipeReader).Read(0x14001335d68?, {0x14001c98000?, 0x0?, 0x0?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/pipe.go:136 +0x24
[2023-08-11][08:52:20][ERROR][app] bufio.(*Scanner).Scan(0x14001335f48)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/bufio/scan.go:214 +0x908
[2023-08-11][08:52:20][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter.func1()
[2023-08-11][08:52:20][ERROR][app] 	internal/singleprogram/postgresql.go:186 +0xb0
[2023-08-11][08:52:20][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter
[2023-08-11][08:52:20][ERROR][app] 	internal/singleprogram/postgresql.go:184 +0x1dc
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 312 [IO wait]:
[2023-08-11][08:52:20][ERROR][app] internal/poll.runtime_pollWait(0x13b9c59f8, 0x72)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/runtime/netpoll.go:305 +0xa0
[2023-08-11][08:52:20][ERROR][app] internal/poll.(*pollDesc).wait(0x1400225a380?, 0x14001cd4000?, 0x0)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
[2023-08-11][08:52:20][ERROR][app] internal/poll.(*pollDesc).waitRead(...)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:89
[2023-08-11][08:52:20][ERROR][app] internal/poll.(*FD).Read(0x1400225a380, {0x14001cd4000, 0xa000, 0xa000})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
[2023-08-11][08:52:20][ERROR][app] net.(*netFD).Read(0x1400225a380, {0x14001cd4000?, 0x140023bb320?, 0xd?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/fd_posix.go:55 +0x28
[2023-08-11][08:52:20][ERROR][app] net.(*conn).Read(0x14000518730, {0x14001cd4000?, 0x14001cd4569?, 0x1030a2306?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/net.go:183 +0x34
[2023-08-11][08:52:20][ERROR][app] crypto/tls.(*atLeastReader).Read(0x14001b9dad0, {0x14001cd4000?, 0x0?, 0x1030a2328?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:787 +0x40
[2023-08-11][08:52:20][ERROR][app] bytes.(*Buffer).ReadFrom(0x140023bb3f8, {0x1100d0f00, 0x14001b9dad0})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/bytes/buffer.go:202 +0x90
[2023-08-11][08:52:20][ERROR][app] crypto/tls.(*Conn).readFromUntil(0x140023bb180, {0x13bc45ab0?, 0x14000518730}, 0x14001cd4571?)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:809 +0xd4
[2023-08-11][08:52:20][ERROR][app] crypto/tls.(*Conn).readRecordOrCCS(0x140023bb180, 0x0)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:616 +0xd8
[2023-08-11][08:52:20][ERROR][app] crypto/tls.(*Conn).readRecord(...)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:582
[2023-08-11][08:52:20][ERROR][app] crypto/tls.(*Conn).Read(0x140023bb180, {0x14002513000, 0x1000, 0x100000001?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:1315 +0x178
[2023-08-11][08:52:20][ERROR][app] bufio.(*Reader).Read(0x140023fed20, {0x14001dfe740, 0x9, 0x140024d2000?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/bufio/bufio.go:237 +0x1e0
[2023-08-11][08:52:20][ERROR][app] io.ReadAtLeast({0x1100cd8e0, 0x140023fed20}, {0x14001dfe740, 0x9, 0x9}, 0x9)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/io.go:332 +0xa0
[2023-08-11][08:52:20][ERROR][app] io.ReadFull(...)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/io/io.go:351
[2023-08-11][08:52:20][ERROR][app] net/http.http2readFrameHeader({0x14001dfe740?, 0x9?, 0x14001c3e330?}, {0x1100cd8e0?, 0x140023fed20?})
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:1565 +0x58
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2Framer).ReadFrame(0x14001dfe700)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:1829 +0x84
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2clientConnReadLoop).run(0x14001dabf88)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8874 +0xfc
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2ClientConn).readLoop(0x14001064600)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8770 +0x5c
[2023-08-11][08:52:20][ERROR][app] created by net/http.(*http2Transport).newClientConn
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7477 +0x920
[2023-08-11][08:52:20][ERROR][app] 
[2023-08-11][08:52:20][ERROR][app] goroutine 340 [select, 5 minutes]:
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2clientStream).writeRequest(0x14001d7d080, 0x14001edd400)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8095 +0x7d4
[2023-08-11][08:52:20][ERROR][app] net/http.(*http2clientStream).doRequest(0x0?, 0x14000512300?)
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7957 +0x20
[2023-08-11][08:52:20][ERROR][app] created by net/http.(*http2ClientConn).RoundTrip
[2023-08-11][08:52:20][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7886 +0x2ec
[2023-08-11][08:52:20][ERROR][app] Cody app backend terminated with exit code 2

**Comment by mrmarbury** [comment]
same. Restarting, deleting caches, re-installing, deleting dot files does not help. It's just unusable.

OS: MacOS 13, CPU: Apple Silicon
Cody App version: any including latest
