### ISSUE TITLE
Just can't initialize Cody app in Mac.

### ISSUE THREAD

**Issue by zhengtuqiang** [sourcegraph/app#70]
<img width="586" alt="image" src="https://github.com/sourcegraph/app/assets/9402724/cc878646-4520-425c-af41-ca08f0a5306a">
<img width="1024" alt="image" src="https://github.com/sourcegraph/app/assets/9402724/dee95ace-37c5-45ef-a621-6f8235d63065">

```
[2023-09-05][17:20:23][ERROR][app] ✱ Sourcegraph App version: 2023.7.11+1384.7d20a90ce7 darwin arm64
[2023-09-05][17:25:23][ERROR][app] panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 296 [running]:
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0x140011fe890?)
[2023-09-05][17:25:23][ERROR][app] 	internal/conf/store.go:175 +0x300
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0x14000a29440)
[2023-09-05][17:25:23][ERROR][app] 	internal/conf/store.go:137 +0x2c
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0x140003947c0, 0x111b6e070)
[2023-09-05][17:25:23][ERROR][app] 	internal/conf/client.go:169 +0x1b8
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x14001cacb40?)
[2023-09-05][17:25:23][ERROR][app] 	internal/conf/client.go:136 +0x28
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0.func2()
[2023-09-05][17:25:23][ERROR][app] 	cmd/symbols/parser/config.go:52 +0x24
[2023-09-05][17:25:23][ERROR][app] created by github.com/sourcegraph/sourcegraph/cmd/symbols/parser.init.0
[2023-09-05][17:25:23][ERROR][app] 	cmd/symbols/parser/config.go:51 +0xe8
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 1 [sync.Cond.Wait]:
[2023-09-05][17:25:23][ERROR][app] sync.runtime_notifyListWait(0x14001d1bb48, 0x5f2)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/runtime/sema.go:517 +0x16c
[2023-09-05][17:25:23][ERROR][app] sync.(*Cond).Wait(0x14001d1bb38)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/sync/cond.go:70 +0xd0
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2pipe).Read(0x14001d1bb30, {0x14003617a2d, 0x485d3, 0x485d3})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:3668 +0x130
[2023-09-05][17:25:23][ERROR][app] net/http.http2transportResponseBody.Read({0x140023bdf78?}, {0x14003617a2d?, 0x11d440a20?, 0x0?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:9157 +0x54
[2023-09-05][17:25:23][ERROR][app] io.ReadAll({0x11d440a20, 0x14001d1bb00})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/io.go:661 +0xe4
[2023-09-05][17:25:23][ERROR][app] io/ioutil.ReadAll(...)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/ioutil/ioutil.go:27
[2023-09-05][17:25:23][ERROR][app] github.com/fergusstrange/embedded-postgres.defaultRemoteFetchStrategy.func1()
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/remote_fetch.go:48 +0x1d8
[2023-09-05][17:25:23][ERROR][app] github.com/fergusstrange/embedded-postgres.(*EmbeddedPostgres).Start(0x14001eaa2d0)
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_fergusstrange_embedded_postgres/embedded_postgres.go:100 +0x264
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.startEmbeddedPostgreSQL({0x111bef970, 0x140024301c0}, {0x140011be780, 0x46})
[2023-09-05][17:25:23][ERROR][app] 	internal/singleprogram/postgresql.go:144 +0x57c
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.initPostgreSQL({0x111bef970, 0x140024301c0}, {0x140011be780?, 0x12?})
[2023-09-05][17:25:23][ERROR][app] 	internal/singleprogram/postgresql.go:39 +0x40
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.Init({0x111bef970, 0x140024301c0})
[2023-09-05][17:25:23][ERROR][app] 	internal/singleprogram/singleprogram.go:106 +0x888
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main.func3(0x140022d4a00?)
[2023-09-05][17:25:23][ERROR][app] 	internal/service/svcmain/svcmain.go:91 +0x80
[2023-09-05][17:25:23][ERROR][app] github.com/urfave/cli/v2.(*Command).Run(0x140022d4a00, 0x14002279e00, {0x14000128000, 0x5, 0x5})
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_urfave_cli_v2/command.go:271 +0x78c
[2023-09-05][17:25:23][ERROR][app] github.com/urfave/cli/v2.(*App).RunContext(0x140005772c0, {0x111bd2778?, 0x14000124008}, {0x14000128000, 0x5, 0x5})
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:333 +0x5a4
[2023-09-05][17:25:23][ERROR][app] github.com/urfave/cli/v2.(*App).Run(...)
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_urfave_cli_v2/app.go:310
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/service/svcmain.Main({0x114372ec0, 0xd, 0xd}, {0x64?, 0x0?}, {0x14000128000?, 0x5, 0x5})
[2023-09-05][17:25:23][ERROR][app] 	internal/service/svcmain/svcmain.go:102 +0x620
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/enterprise/cmd/sourcegraph/enterprisecmd.MainEnterprise(...)
[2023-09-05][17:25:23][ERROR][app] 	enterprise/cmd/sourcegraph/enterprisecmd/enterprisecmd.go:15
[2023-09-05][17:25:23][ERROR][app] main.main()
[2023-09-05][17:25:23][ERROR][app] 	/private/var/tmp/_bazel_ec2-user/58ad2e50dcfb9c20da085cd0810f895a/sandbox/darwin-sandbox/5637/execroot/__main__/enterprise/cmd/sourcegraph/main.go:50 +0x118
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 26 [select]:
[2023-09-05][17:25:23][ERROR][app] go.opencensus.io/stats/view.(*worker).start(0x140002bac80)
[2023-09-05][17:25:23][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:292 +0x88
[2023-09-05][17:25:23][ERROR][app] created by go.opencensus.io/stats/view.init.0
[2023-09-05][17:25:23][ERROR][app] 	external/io_opencensus_go/stats/view/worker.go:34 +0xa4
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 252 [chan receive]:
[2023-09-05][17:25:23][ERROR][app] github.com/golang/glog.(*loggingT).flushDaemon(0x140022023f0?)
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_golang_glog/glog.go:882 +0x5c
[2023-09-05][17:25:23][ERROR][app] created by github.com/golang/glog.init.0
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_golang_glog/glog.go:410 +0x200
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 144 [select, 5 minutes]:
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do(0x140011c46d8, 0x20)
[2023-09-05][17:25:23][ERROR][app] 	internal/limiter/mutable.go:94 +0x14c
[2023-09-05][17:25:23][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/limiter.NewMutable
[2023-09-05][17:25:23][ERROR][app] 	internal/limiter/mutable.go:38 +0x108
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 323 [select]:
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume(0x140022d3260)
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:59 +0xa8
[2023-09-05][17:25:23][ERROR][app] created by github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).start
[2023-09-05][17:25:23][ERROR][app] 	external/com_github_sourcegraph_log/internal/sinkcores/sentrycore/worker.go:51 +0x60
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 324 [select, 5 minutes]:
[2023-09-05][17:25:23][ERROR][app] io.(*pipe).read(0x140022ce960, {0x1400237c000, 0x1000, 0x0?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/pipe.go:57 +0x84
[2023-09-05][17:25:23][ERROR][app] io.(*PipeReader).Read(0x140000a4d68?, {0x1400237c000?, 0x5000?, 0x0?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/pipe.go:136 +0x24
[2023-09-05][17:25:23][ERROR][app] bufio.(*Scanner).Scan(0x140000b1f48)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/bufio/scan.go:214 +0x908
[2023-09-05][17:25:23][ERROR][app] github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter.func1()
[2023-09-05][17:25:23][ERROR][app] 	internal/singleprogram/postgresql.go:186 +0xb0
[2023-09-05][17:25:23][ERROR][app] created by github.com/sourcegraph/sourcegraph/internal/singleprogram.debugLogLinesWriter
[2023-09-05][17:25:23][ERROR][app] 	internal/singleprogram/postgresql.go:184 +0x1dc
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 329 [select, 5 minutes]:
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2clientStream).writeRequest(0x14001d1bb00, 0x140011cb900)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8095 +0x7d4
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2clientStream).doRequest(0x0?, 0x0?)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7957 +0x20
[2023-09-05][17:25:23][ERROR][app] created by net/http.(*http2ClientConn).RoundTrip
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7886 +0x2ec
[2023-09-05][17:25:23][ERROR][app] 
[2023-09-05][17:25:23][ERROR][app] goroutine 328 [IO wait]:
[2023-09-05][17:25:23][ERROR][app] internal/poll.runtime_pollWait(0x13e0580a8, 0x72)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/runtime/netpoll.go:305 +0xa0
[2023-09-05][17:25:23][ERROR][app] internal/poll.(*pollDesc).wait(0x1400233c400?, 0x14000d1b300?, 0x0)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
[2023-09-05][17:25:23][ERROR][app] internal/poll.(*pollDesc).waitRead(...)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/internal/poll/fd_poll_runtime.go:89
[2023-09-05][17:25:23][ERROR][app] internal/poll.(*FD).Read(0x1400233c400, {0x14000d1b300, 0x1300, 0x1300})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/internal/poll/fd_unix.go:167 +0x1e0
[2023-09-05][17:25:23][ERROR][app] net.(*netFD).Read(0x1400233c400, {0x14000d1b300?, 0x14000d1b869?, 0x104956206?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/fd_posix.go:55 +0x28
[2023-09-05][17:25:23][ERROR][app] net.(*conn).Read(0x140011fe9e8, {0x14000d1b300?, 0x8?, 0x12fb?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/net.go:183 +0x34
[2023-09-05][17:25:23][ERROR][app] crypto/tls.(*atLeastReader).Read(0x1400013dc20, {0x14000d1b300?, 0x0?, 0x104b56328?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:787 +0x40
[2023-09-05][17:25:23][ERROR][app] bytes.(*Buffer).ReadFrom(0x140022cd078, {0x111b84f00, 0x1400013dc20})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/bytes/buffer.go:202 +0x90
[2023-09-05][17:25:23][ERROR][app] crypto/tls.(*Conn).readFromUntil(0x140022cce00, {0x13e058678?, 0x140011fe9e8}, 0xd9c?)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:809 +0xd4
[2023-09-05][17:25:23][ERROR][app] crypto/tls.(*Conn).readRecordOrCCS(0x140022cce00, 0x0)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:616 +0xd8
[2023-09-05][17:25:23][ERROR][app] crypto/tls.(*Conn).readRecord(...)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:582
[2023-09-05][17:25:23][ERROR][app] crypto/tls.(*Conn).Read(0x140022cce00, {0x1400243c000, 0x1000, 0x1117d8fc0?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/crypto/tls/conn.go:1315 +0x178
[2023-09-05][17:25:23][ERROR][app] bufio.(*Reader).Read(0x140022cf560, {0x1400244a53e, 0x547, 0x9?})
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/bufio/bufio.go:237 +0x1e0
[2023-09-05][17:25:23][ERROR][app] io.ReadAtLeast({0x111b818e0, 0x140022cf560}, {0x1400244a000, 0xa85, 0x4000}, 0xa85)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/io.go:332 +0xa0
[2023-09-05][17:25:23][ERROR][app] io.ReadFull(...)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/io/io.go:351
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2Framer).ReadFrame(0x140022b50a0)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:1837 +0x10c
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2clientConnReadLoop).run(0x14002485f88)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8874 +0xfc
[2023-09-05][17:25:23][ERROR][app] net/http.(*http2ClientConn).readLoop(0x14001d1b980)
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:8770 +0x5c
[2023-09-05][17:25:23][ERROR][app] created by net/http.(*http2Transport).newClientConn
[2023-09-05][17:25:23][ERROR][app] 	GOROOT/src/net/http/h2_bundle.go:7477 +0x920
[2023-09-05][17:25:23][ERROR][app] Cody app backend terminated with exit code 2
```

**Comment by zhengtuqiang** [comment]
JDK upgrade form 1.8 to 17 solve this problem.
